version: '3'

services:
  webserver:
    build: .
    container_name: web_cadastro_cliente
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/
    depends_on:
      - db
  db:
    container_name: db_cadastro_cliente
    image: mysql
    restart: on-failure
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=alter-solutions
      - MYSQL_DATABASE=alter-solutions
